# Generated by Django 2.0.1 on 2018-04-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedoor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackProfile',
            fields=[
                ('slack_id', models.CharField(blank=True, max_length=1000, primary_key=True, serialize=False)),
                ('prim_key', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
