# Generated by Django 2.0.1 on 2019-01-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedoor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10),
        ),
        migrations.AddField(
            model_name='company',
            name='num_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
