# Generated by Django 2.0.1 on 2018-03-08 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codedoor', '0002_auto_20180307_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='company',
        ),
    ]
