# Generated by Django 2.0.1 on 2019-01-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedoor', '0002_auto_20190101_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='avg_rating',
            field=models.DecimalField(decimal_places=5, default=-1, max_digits=10),
        ),
    ]
