# Generated by Django 2.0.1 on 2018-03-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedoor', '0003_remove_question_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
