# Generated by Django 2.0.1 on 2018-04-12 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codedoor', '0003_auto_20180408_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codedoor.Application')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codedoor.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codedoor.Profile')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codedoor.Review')),
            ],
        ),
    ]
