# Generated by Django 2.0.1 on 2018-04-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedoor', '0005_reviewcomment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationcomment',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
