# Generated by Django 2.0.1 on 2018-03-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedoor', '0005_auto_20180319_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.URLField(blank=True, null=True),
        ),
    ]
